import { CodeStatus, LootCode, RewardType, NewsCategory, NewsItem } from './types';

export const REDEEM_URL = 'https://redeem.fcm.ea.com/';

export const MOCK_CODES: LootCode[] = [
  {
    id: '1',
    code: 'SEACREATOR',
    reward: '1,500 Gems',
    rewardType: RewardType.GEMS,
    expiresAt: new Date(Date.now() + 86400000 * 3).toISOString(), // Active for 3 more days
    createdAt: new Date(Date.now() - 172800000).toISOString(), // 2 days ago
    status: CodeStatus.ACTIVE,
    upvotes: 2450,
    downvotes: 12,
    author: 'EA_Official',
    source: 'X (@EASFCMobile)',
    sourceUrl: 'https://twitter.com/EASFCMobile',
    isSystemVerified: true,
    lastVerifiedAt: new Date().toISOString(),
  },
  {
    id: '2',
    code: 'FESTIVEGIFT',
    reward: 'Reward Pack',
    rewardType: RewardType.PACK,
    expiresAt: new Date(Date.now() - 86400000).toISOString(), // Expired yesterday
    createdAt: new Date(Date.now() - 432000000).toISOString(), // 5 days ago
    status: CodeStatus.EXPIRED,
    upvotes: 5600,
    downvotes: 120,
    author: 'AutoScraper_Bot',
    source: 'X (@EASFCMobile)',
    sourceUrl: 'https://twitter.com/EASFCMobile',
    isSystemVerified: true,
    lastVerifiedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '3',
    code: 'KOMENTATORID',
    reward: '2,000 Gems',
    rewardType: RewardType.GEMS,
    expiresAt: new Date(Date.now() - 172800000).toISOString(),
    createdAt: new Date(Date.now() - 864000000).toISOString(),
    status: CodeStatus.EXPIRED,
    upvotes: 4100,
    downvotes: 45,
    author: 'CommunityMod',
    source: 'X (@FCMobile_News)',
    isSystemVerified: true,
  },
  {
    id: '4',
    code: 'MOSTWONDERFULTIME',
    reward: 'Item Pack',
    rewardType: RewardType.PACK,
    expiresAt: new Date(Date.now() - 259200000).toISOString(),
    createdAt: new Date(Date.now() - 950400000).toISOString(),
    status: CodeStatus.EXPIRED,
    upvotes: 3200,
    downvotes: 80,
    author: 'EA_Official',
    source: 'X (@EASFCMobile)',
    isSystemVerified: true,
  },
  {
    id: '5',
    code: 'FCMELITE',
    reward: 'Glorious Eras Player',
    rewardType: RewardType.PLAYER,
    expiresAt: new Date(Date.now() - 604800000).toISOString(),
    createdAt: new Date(Date.now() - 1209600000).toISOString(),
    status: CodeStatus.EXPIRED,
    upvotes: 8900,
    downvotes: 300,
    author: 'AutoScraper_Bot',
    source: 'X (@EASFCMobile)',
    isSystemVerified: true,
  },
  {
    id: '6',
    code: 'MLSCUP25',
    reward: 'Gems & Rankup Points',
    rewardType: RewardType.GEMS,
    expiresAt: new Date(Date.now() - 1209600000).toISOString(),
    createdAt: new Date(Date.now() - 1814400000).toISOString(),
    status: CodeStatus.EXPIRED,
    upvotes: 1200,
    downvotes: 50,
    author: 'EA_Official',
    source: 'X (@EASFCMobile)',
    isSystemVerified: true,
  },
  {
    id: '7',
    code: 'CYBERWEEK25',
    reward: 'Player Item + Coins',
    rewardType: RewardType.PLAYER,
    expiresAt: new Date(Date.now() - 1509600000).toISOString(),
    createdAt: new Date(Date.now() - 2419200000).toISOString(),
    status: CodeStatus.EXPIRED,
    upvotes: 2100,
    downvotes: 20,
    author: 'EA_Official',
    source: 'X (@EASFCMobile)',
    isSystemVerified: true,
  },
];

export const MOCK_NEWS: NewsItem[] = [
  {
    id: '1',
    title: "TOTY 26 Coming Soon",
    date: "Jan 15, 2026",
    category: NewsCategory.UPCOMING,
    description: "Get ready for the biggest event of the year! Team of the Year (TOTY) arrives mid-January. Save your gems and fodder for the ultimate squad upgrades.",
    iconType: 'TROPHY',
  },
  {
    id: '2',
    title: "Festive Fixtures",
    date: "Live Now",
    category: NewsCategory.CURRENT_EVENT,
    description: "Celebrate the holidays with Festive Fixtures! Complete daily skill games and matches to earn exclusive Winter Wildcards and Mascheranos.",
    iconType: 'FLAME',
  },
  {
    id: '3',
    title: "Record Breakers",
    date: "Recent",
    category: NewsCategory.EVENT,
    description: "New cards celebrating players who shattered records this season. Look out for boosted stats on pace and shooting.",
    iconType: 'ZAP',
  }
];